apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecsdemo-crystal
  namespace: argocd
spec:
  destinations:
  - namespace: ecsdemo-crystal
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:aws-containers/ecsdemo-crystal.git
